#!/bin/bash

source "$HOME/.config/sketchybar/palette.sh"

SILVER="${palette[7]}"
GREY="${palette[8]}"
BORDER="${GREY}"
BORDER_HIGHLIGHT="$SILVER"

rounded=(
    order=below
    style=round
    width=1.0
    hidpi=on
)

squared=(
    hidpi=off
    order=above
    width=8.0
    style=square
)

theme=(
    active_color=$BORDER_HIGHLIGHT
    inactive_color=$BORDER
    background_color=$background
)

options=(
    ${squared[@]}
    ${theme[@]}
)

borders "${options[@]}"
