#!/usr/bin/env zsh
# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Section
# ------------------------------------------------------------------------------

  SPACESHIP_PROMPT_ORDER=(
    dir
    git
    line_sep
    char
  )

# ------------------------------------------------------------------------------
# Generate Random Emojis
# ------------------------------------------------------------------------------

# SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_DIR_TRUNC='1' # show only last directory
SPACESHIP_DIR_TRUNC_PREFIX="┌─[%b "
SPACESHIP_CHAR_SYMBOL="└ %b"
SPACESHIP_DIR_SUFFIX=" ] "

# EXIT CODE
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_PREFIX="("
SPACESHIP_EXIT_CODE_SUFFIX=") "
SPACESHIP_EXIT_CODE_SYMBOL="✘ "
SPACESHIP_EXIT_CODE_COLOR="red"
