#!/usr/bin/env zsh

# init antidote plugin manager
export BREW_HOME=$(brew --prefix)
export ANTIDOTE_HOME="$BREW_HOME/opt/antidote/share/antidote"
source $ANTIDOTE_HOME/antidote.zsh

zsh_plugins=~/.zsh_plugins.zsh

export NVM_LAZY_LOAD=true
export NVM_COMPLETION=true

bindkey '^[[A' history-substring-search-up;
bindkey '^[[B' history-substring-search-down;

ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(forward-word forward-char)
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(end-of-line)

antidote load ~/.zsh_plugins.txt

source ~/.zsh_plugins.zsh

