  
#!/usr/bin/env zsh

# - Exports
export ZSH=$HOME/.oh-my-zsh

# --- Source
# source ~/.zsh_env
# source ~/.zsh_fzf_extra
# source ~/.fzf.zsh
# source ~/.zsh_misc
# source ~/.zsh_keybinds
# source ~/.zsh_functions

source ~/.zsh_plug
source ~/.zsh_aliases
source ~/.zsh_theme 2>/dev/null

# source $ZSH/oh-my-zsh.sh

(( $+commands[thefuck] )) && source <(thefuck --alias 2>/dev/null)
# (( $+commands[pyenv]   )) && source <(pyenv init -)

return 0