#!usr/bin/env zsh

# Get the current Ruby version
# ruby_version=$(rvm current)

# - Exports
export ZSH=$HOME/.oh-my-zsh
export ZPLUG_HOME=$(brew --prefix)/opt/zplug
# export PATH="$PATH:/opt/homebrew/opt/ruby/bin" # Sets path for new version of ruby
export PATH="/opt/homebrew/opt/ruby/bin:$PATH" # Sets path for new version of ruby
# export PATH="/usr/local/opt/ruby/bin:$PATH" # Sets path for new version of ruby
# export GEM_HOME="$HOME/.gem"

# android studio
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Force Java to Zulu version 11
export JAVA_HOME=$(/usr/libexec/java_home -v 11)
export PATH=$JAVA_HOME/bin:$PATH

# Change ruby path from default to brew installed.
# export PATH=$PATH:$(ruby -e 'puts Gem.bindir')
# export PATH=$(ruby -e 'puts Gem.bindir'):$PATH

# Left as a reminder for potential future files
# --- Source
# source ~/.zsh_env
# source ~/.zsh_fzf_extra
# source ~/.zsh_misc
# source ~/.zsh_keybinds
# source ~/.zsh_functions

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# source ruby version manager scripts to allow default ruby version to be set
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Adds colorls autocomplete
source $(dirname $(gem which colorls))/tab_complete.sh

# exports zPlug
source $ZPLUG_HOME/init.zsh

source ~/.zsh_plug
source ~/.zsh_aliases
source ~/.zsh_theme 2>/dev/null
# source ~/.export

# oh-my-zsh conflicts with custom theme
# source $ZSH/oh-my-zsh.sh

(( $+commands[thefuck] )) && source <(thefuck --alias 2>/dev/null)
# (( $+commands[pyenv]   )) && source <(pyenv init -)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pyenv for managin python versions
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Run alias to turn off mouse acceleration
mouseAccOff

# allow key repeat – necessary for h,j,k,l keys in vscode
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

## BACKUP
export PATH=$(ruby -e 'puts Gem.bindir'):$PATH

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
# export PATH="$HOME/.rvm/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin"

