SPACING=8
ITEM_HEIGHT=20
BAR_HEIGHT=32
BORDER_WIDTH=2
BORDER_RADIUS=11
FONT="LiterationMono Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDING=12 # All paddings use this value (icon, label, background)
# LABEL_SM="$FONT:book:10.0"
# LABEL_MD="$FONT:book:12.0"
# LABEL_LG="$FONT:book:14.0"
# ICON_SM="$FONT:bold:12.0"
# ICON_MD="$FONT:bold:14.0"
# ICON_LG="$FONT:bold:16.0"
